image: Visual Studio 2017

init:
  - git config --global core.autocrlf input

clone_folder: C:\Projects\Utilities
shallow_clone: true

matrix:
  fast_finish: false

platform:
  - x86
  - x64

configuration:
  - Debug
  - Release

environment:
  MSVC_DEFAULT_OPTIONS: ON
  matrix:
    - TOOLCHAIN: msvc15

install:
  - call CI\AppVeyor\SetEnviroment.bat %TOOLCHAIN% %PLATFORM%

build_script:
    - mkdir build
    - cd build
    - cmake .. %CMAKE_CONFIGURE_FLAGS% -DCMAKE_BUILD_TYPE=%configuration%
    - cmake --build . 
#%CMAKE_BUILD_FLAGS%

test_script:
    #- ctest -C %CONFIGURATION% --output-on-failure