image: Visual Studio 2017

init:
    - git config --global core.autocrlf input

clone_folder: c:\projects\utilities # выбираем локальную директорию для клонирования
shallow_clone: true              # копируем только последний коммит, без истории (git clone --depth 1)

matrix:
    fast_finish: false           # не останавливаемся после возникновения ошибки в каком-то из заданий

platform:
    - x64
    - x86

configuration:
    - Debug
    - Release

environment:
    matrix:
        - TOOLCHAIN: msvc15

install:
    # скрипт настройки среды и установки зависимостей:
    #- call ci\appveyor\set-env.bat %TOOLCHAIN% %PLATFORM%

    #- appveyor DownloadFile <url> -FileName <local-file>
    #- 7z e -y <local-file> -o<local-dir>
    #- ...

build_script:
    # скрипт сборки проекта:
    - mkdir build
    - cd build
    - cmake .. %CMAKE_CONFIGURE_FLAGS%
    - cmake --build . %CMAKE_BUILD_FLAGS%

test_script:
    # скрипт тестирования проекта:
    #- ctest -C %CONFIGURATION% --output-on-failure