image: Visual Studio 2017

init:
  - git config --global core.autocrlf input

clone_folder: C:\Projects\Utilities
shallow_clone: true

matrix:
  fast_finish: false

platform:
  - x86
  - x64

configuration:
  - Debug
  - Release

environment:
  MSVC_DEFAULT_OPTIONS: ON
  BOOST_INCLUDE_DIRS: C:\Libraries\boost_1_64_0
  matrix:
    - TOOLCHAIN: msvc15


#environment:
    #matrix:
      #- TOOLCHAIN: msvc15
      #- MSVC_DEFAULT_OPTIONS: ON
 #     - BOOST_ROOT: C:\Libraries\boost_1_64_0
#      - BOOST_LIBRARYDIR: C:\Libraries\boost_1_64_0\lib32-msvc-15.0

install:
  - call CI\AppVeyor\SetEnviroment.bat %TOOLCHAIN% %PLATFORM%

build_script:
    - mkdir build
    - cd build
    - cmake .. %CMAKE_CONFIGURE_FLAGS% -D"%BOOST_INCLUDE_DIRS%"
    - cmake --build . 
#%CMAKE_BUILD_FLAGS%

test_script:
    #- ctest -C %CONFIGURATION% --output-on-failure