image: Visual Studio 2017

init:
  - git config --global core.autocrlf input

clone_folder: C:\Projects\Utilities
shallow_clone: true

matrix:
  fast_finish: false

platform:
  - x86
  - x64

configuration:
  - Debug
  - Release

environment:
  MSVC_DEFAULT_OPTIONS: ON
  BOOST_ROOT: C:\Libraries\boost_1_64_0
  BOOST_LIBRARYDIR: C:\Libraries\boost_1_64_0\stage\lib
  matrix:
    - TOOLCHAIN: msvc15

install:
  - call CI\AppVeyor\SetEnviroment.bat %TOOLCHAIN% %PLATFORM%

build_script:
    - mkdir build
    - cd build
   # - cmake .. %CMAKE_CONFIGURE_FLAGS% -DBOOST_INCLUDE_DIRS=%BOOST_INCLUDE_DIRS% -D
    - cmake .. %CMAKE_CONFIGURE_FLAGS% -DCMAKE_BUILD_TYPE=%configuration% -DBUILD_SHARED_LIBS=ON -DBOOST_ROOT="%BOOST_ROOT%" -DINCLUDE="%BOOST_ROOT%"
    - cmake --build . 
#%CMAKE_BUILD_FLAGS%

test_script:
    #- ctest -C %CONFIGURATION% --output-on-failure