image: Visual Studio 2017

init:
  - git config --global core.autocrlf input

clone_folder: C:\Projects\Cpp-Utilities
shallow_clone: true

matrix:
  fast_finish: false

platform:
  - x86
  - x64

configuration:
  - Debug
  - Release

environment:
  MSVC_DEFAULT_OPTIONS: ON
  matrix:
    - TOOLCHAIN: msvc15
  GITHUB_TOKEN:
    secure: MeZRb+x5xfxO5jH93yXs5Tl9MDmH48nmpMF/i5ouAV/frSSonzqDUZmYg8oMMMI8
  APPVEYOR_API_TOKEN:
    secure: eXiEH+/7OgWrbLNGD3aeMGOCsUN5MqXxgRMYci+rCMw=	

before_build:
  - choco install opencover.portable
  - choco install codecov

install:
  - call CI\AppVeyor\SetEnviroment.bat %TOOLCHAIN% %PLATFORM%

build_script:
  - mkdir build
  - cd build
  - cmake .. %CMAKE_CONFIGURE_FLAGS% 
  - cmake --build . %CMAKE_BUILD_FLAGS%
  # --config %CONFIGURATION%

test_script:
#  - OpenCover.Console.exe -register:user -target:"%xunit20%\xunit.console.x86.exe" -targetargs:".\MyUnitTests\bin\Debug\MyUnitTests.dll -noshadow" -filter:"+[UnitTestTargetProject*]* -[MyUnitTests*]*" -output:".\MyProject_coverage.xml"
#  - codecov -f "MyProject_coverage.xml
#   - cmake .. %CMAKE_CONFIGURE_FLAGS%
  - ctest -C %CONFIGURATION% --output-on-failure
  - .\bin\%CONFIGURATION%\TestCommon.exe
  - .\bin\%CONFIGURATION%\TestThreadPool.exe

after_test:
  - bash <(curl -s https://codecov.io/bash)
#test_script:    #- ctest -C %CONFIGURATION% --output-on-failure