dist: trusty
language: cpp
sudo: required

os:
  - linux
  #- osx

compiler:
  - gcc

env:
  - TARGET_CPU=x86 BUILD_CONFIGURATION=debug
  - TARGET_CPU=x86 BUILD_CONFIGURATION=release
  - TARGET_CPU=x64 BUILD_CONFIGURATION=debug
  - TARGET_CPU=x64 BUILD_CONFIGURATION=release
 # - TARGET_CPU=amd64 BUILD_CONFIGURATION=Debug
 # - TARGET_CPU=amd64 BUILD_CONFIGURATION=Release

# matrix:
# addons:
#  apt:
#    sources:
#      - boost-latest
#      - ubuntu-toolchain-r-test
#    packages:
#      - libboost1.55-all-dev
 
before_install:
  - pip install --user cpp-coveralls

install:
  - bash CI/Travis/InstallCompilers.sh
  - bash CI/Travis/InstallDependencies.sh
  # sudo apt-get install libboost1.55-all-dev
  
script:
  - ./configure --enable-gcov && make && make check

  - mkdir build
  - cd build
  - cmake .. -DTARGET_CPU=$TARGET_CPU -DCMAKE_BUILD_TYPE=$BUILD_CONFIGURATION
  - make
  
after_success:
  - coveralls --exclude lib --exclude tests --gcov-options '\-lp'
  #--exclude test --exclude googletest --root . --build-root ".build/debug" --gcov-options '\-lp'
