dist: trusty
language: cpp
sudo: required

os:
  - linux
  #- osx

compiler:
  - gcc
   
# addons:
#  apt:
#    sources:
#      - boost-latest
#      - ubuntu-toolchain-r-test
#    packages:
#      - libboost1.55-all-dev

env:
  - TARGET_CPU=x86 BUILD_CONFIGURATION=debug
  - TARGET_CPU=x86 BUILD_CONFIGURATION=release
  - TARGET_CPU=x64 BUILD_CONFIGURATION=debug
  - TARGET_CPU=x64 BUILD_CONFIGURATION=release
 #   - TARGET_CPU=amd64 BUILD_CONFIGURATION=Debug
 #   - TARGET_CPU=amd64 BUILD_CONFIGURATION=Release

before_install:  
  - bash CI/Travis/InstallCompilers.sh

install: 
  - bash CI/Travis/InstallDependencies.sh
  # sudo apt-get install libboost1.55-all-dev
  
script:
  - mkdir build
  - cd build
  - cmake .. -DTARGET_CPU=$TARGET_CPU -DCMAKE_BUILD_TYPE=$BUILD_CONFIGURATION
  - make
