dist: trusty
language: cpp
sudo: required

os:
  - linux
  #- osx

compiler:
  - gcc

env:
  - TARGET_CPU=x86 BUILD_CONFIGURATION=debug
  - TARGET_CPU=x86 BUILD_CONFIGURATION=release
  - TARGET_CPU=x64 BUILD_CONFIGURATION=debug
  - TARGET_CPU=x64 BUILD_CONFIGURATION=release
 # - TARGET_CPU=amd64 BUILD_CONFIGURATION=Debug
 # - TARGET_CPU=amd64 BUILD_CONFIGURATION=Release

# matrix:
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      # - boost-latest
    packages:
      - cmake
      - lcov
      # - libboost1.55-all-dev
 
before_install:

install:
  - bash CI/Travis/InstallCompilers.sh
  - bash CI/Travis/InstallDependencies.sh
  
script:
  - mkdir -p build
  - cd build
  - cmake .. -DTARGET_CPU=$TARGET_CPU -DCMAKE_BUILD_TYPE=$BUILD_CONFIGURATION
  - make -j8
#  - make -j8 TestThreadPool
  - ctest
 
after_success:  
  # Creating report
  - cd ${TRAVIS_BUILD_DIR}
  - lcov --directory . --capture --output-file coverage.info # capture coverage info
  - lcov --remove coverage.info '/usr/*' --output-file coverage.info # filter out system
  - lcov --list coverage.info #debug info
  # Uploading report to CodeCov
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
  
notifications:
  email: false
