language: cpp
sudo: required

os:
    - linux

compiler:
    - gcc

env:
    - TARGET_CPU=x86 BUILD_CONFIGURATION=Debug
    - TARGET_CPU=x86 BUILD_CONFIGURATION=Release
    - TARGET_CPU=x64 BUILD_CONFIGURATION=Debug
    - TARGET_CPU=x64 BUILD_CONFIGURATION=Release
    - TARGET_CPU=amd64 BUILD_CONFIGURATION=Debug
    - TARGET_CPU=amd64 BUILD_CONFIGURATION=Release

before_install:  
  # sudo apt-add-repository "deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-4.0 main"
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get install -qq g++-7
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90
  
install: 
  #- sudo apt-get install --allow-unauthenticated -qq clang++-4.0
  #- export CXX="clang++-4.0"

  - sudo apt-get update -qq
  - sudo apt-get install libboost-all-dev

script:
    - mkdir build
    - cd build
    - cmake .. -DTARGET_CPU=$TARGET_CPU -DCMAKE_BUILD_TYPE=$BUILD_CONFIGURATION
    - make