dist: trusty
language: cpp
sudo: required

os:
    - linux

compiler:
    - gcc
   
# addons:
#  apt:
#    sources:
#      - boost-latest
#      - ubuntu-toolchain-r-test
#    packages:
#      - libboost1.55-all-dev

env:
    - TARGET_CPU=x86 BUILD_CONFIGURATION=debug
    - TARGET_CPU=x86 BUILD_CONFIGURATION=release
 #   - TARGET_CPU=x64 BUILD_CONFIGURATION=Debug
 #   - TARGET_CPU=x64 BUILD_CONFIGURATION=Release
 #   - TARGET_CPU=amd64 BUILD_CONFIGURATION=Debug
 #   - TARGET_CPU=amd64 BUILD_CONFIGURATION=Release

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  # http://ppa.launchpad.net/banshee-team/ppa/ubuntu/dists/
  - sudo apt-get update -qq
  
install: 
  #- sudo apt-add-repository "deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-4.0 main"
  #- sudo apt-get install --allow-unauthenticated -qq clang++-4.0
  #- export CXX="clang++-4.0"
 
  - sudo apt-get install -qq g++-7
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90
  - if [ "$CXX" = "g++" ]; then export CXX="g++-7"; fi
  
  - sudo wget -O boost_1_64_0.tar.gz http://sourceforge.net/projects/boost/files/boost/1.64.0/boost_1_64_0.tar.gz/download
  - sudo tar xzf boost_1_64_0.tar.gz
  - cd boost_1_64_0/
  - sudo ./bootstrap.sh --with-libraries=filesystem,system
  - sudo ./b2 toolset=gcc link=shared threading=multi variant=$BUILD_CONFIGURATION
  - sudo ./b2 install
  - cd ..
  #- sudo apt-get install libboost1.55-all-dev
  
script:
    - mkdir build
    - cd build
    - cmake .. -DTARGET_CPU=$TARGET_CPU -DCMAKE_BUILD_TYPE=$BUILD_CONFIGURATION
    - make
