dist: trusty
language: cpp
sudo: required

os:
  - linux
  #- osx

compiler:
  - gcc

env:
  - TARGET_CPU=x86 BUILD_CONFIGURATION=debug   COVERAGE=On
  - TARGET_CPU=x86 BUILD_CONFIGURATION=release COVERAGE=Off
  - TARGET_CPU=x64 BUILD_CONFIGURATION=debug   COVERAGE=On
  - TARGET_CPU=x64 BUILD_CONFIGURATION=release COVERAGE=Off
 # - TARGET_CPU=amd64 BUILD_CONFIGURATION=Debug
 # - TARGET_CPU=amd64 BUILD_CONFIGURATION=Release

# matrix:
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - lcov
      - cppcheck
 
before_install:

install:
  - bash CI/Travis/InstallCompilers.sh
  - bash CI/Travis/InstallDependencies.sh
  
script:
  - bash CI/Travis/Build.sh

after_success:
  
notifications:
  email: false
