dist: trusty
language: cpp
sudo: required

os:
    - linux

compiler:
    - gcc

cache:
  directories:
    - ${TRAVIS_BUILD_DIR}/deps/llvm-3.6.2
    - ${TRAVIS_BUILD_DIR}/deps/llvm-3.7.1
    - ${TRAVIS_BUILD_DIR}/deps/llvm-3.8.0
    - ${TRAVIS_BUILD_DIR}/deps/llvm-3.9.0
    - ${TRAVIS_BUILD_DIR}/deps/boost-1.59.0
    - ${TRAVIS_BUILD_DIR}/deps/boost-1.60.0
    - ${TRAVIS_BUILD_DIR}/deps/boost-1.61.0
    - ${TRAVIS_BUILD_DIR}/deps/boost-1.62.0
    - ${TRAVIS_BUILD_DIR}/deps/boost-1.63.0
    
addons:
  apt:
    sources:
#      - boost-latest
      - ubuntu-toolchain-r-test
#      - nschloe/boost-nightly
#    packages:
#      - libboost1.55-all-dev

env:
    - TARGET_CPU=x86 BUILD_CONFIGURATION=Debug
    - TARGET_CPU=x86 BUILD_CONFIGURATION=Release
 #   - TARGET_CPU=x64 BUILD_CONFIGURATION=Debug
 #   - TARGET_CPU=x64 BUILD_CONFIGURATION=Release
 #   - TARGET_CPU=amd64 BUILD_CONFIGURATION=Debug
 #   - TARGET_CPU=amd64 BUILD_CONFIGURATION=Release

before_install:
  #- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  # http://ppa.launchpad.net/banshee-team/ppa/ubuntu/dists/
  #- sudo add-apt-repository -y ppa:nschloe/boost-nightly
  #- sudo apt-get update -qq
  #- sudo apt-get install libboost-all-dev
 # - sudo apt-get install libboost1.64-all-dev
 
#  - sudo apt-get install libboost-system1.64-dev
 # - sudo apt-get install libboost-filesystem1.64-dev
  - sudo wget -O boost_1_64_0.tar.gz http://sourceforge.net/projects/boost/files/boost/1.64.0/boost_1_64_0.tar.gz/download
  - sudo tar xzf boost_1_64_0.tar.gz
  - cd boost_1_64_0/
  - sudo ./bootstrap.sh --with-libraries=program_options,filesystem,system
  - sudo ./b2 link=shared threading=multi variant=release
  - sudo ./b2 install

install: 
  #- sudo apt-add-repository "deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-4.0 main"
  #- sudo apt-get install --allow-unauthenticated -qq clang++-4.0
  #- export CXX="clang++-4.0"
 
  
#  - sudo apt-get install libboost-all-dev
 # - sudo apt-get install libboost-system1.64-dev
#  - sudo apt-get install libboost-filesystem1.64-dev

  - sudo apt-get install -qq g++-7
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90
  - if [ "$CXX" = "g++" ]; then export CXX="g++-7"; fi
  
script:
    - mkdir build
    - cd build
    - cmake .. -DTARGET_CPU=$TARGET_CPU -DCMAKE_BUILD_TYPE=$BUILD_CONFIGURATION
    - make
