language: cpp
sudo: required
dist: trusty

os:
    - linux

compiler:
    - gcc
    
addons:
  apt:
    sources:
      - boost-latest
      #- ubuntu-toolchain-r-test
    packages:
      - libboost1.55-all-dev

env:
    - TARGET_CPU=x86 BUILD_CONFIGURATION=Debug
    - TARGET_CPU=x86 BUILD_CONFIGURATION=Release
 #   - TARGET_CPU=x64 BUILD_CONFIGURATION=Debug
 #   - TARGET_CPU=x64 BUILD_CONFIGURATION=Release
 #   - TARGET_CPU=amd64 BUILD_CONFIGURATION=Debug
 #   - TARGET_CPU=amd64 BUILD_CONFIGURATION=Release

before_install:
  #- sudo apt-get install libboost-all-dev
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test #-y
  # http://ppa.launchpad.net/banshee-team/ppa/ubuntu/dists/
  - sudo apt-get update #-qq

install: 
  #- sudo apt-add-repository "deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-4.0 main"
  #- sudo apt-get install --allow-unauthenticated -qq clang++-4.0
  #- export CXX="clang++-4.0"
  
  - sudo apt-get install -qq g++-7
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90
  - if [ "$CXX" = "g++" ]; then export CXX="g++-7"; fi
  
  #- sudo apt-get install libboost1.55-all-dev
  
script:
    - mkdir build
    - cd build
    - cmake .. -DTARGET_CPU=$TARGET_CPU -DCMAKE_BUILD_TYPE=$BUILD_CONFIGURATION
    - make
